name: Spotify Ingestion

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Spotify ingestion
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: python spotify_recently_played.py
